import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

type Lang = "en" | "ru" | "kz";

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Auth
    welcome: "Welcome",
    welcomeSubtitle: "Manage projects, tasks, and documents in one place.",
    logIn: "Log In",
    signUp: "Sign Up",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    continue: "Continue",
    createAccount: "Create Account",
    noAccount: "No account? Sign Up",
    hasAccount: "Already have an account? Log In",
    // Tabs
    home: "Home",
    myProjects: "My Projects",
    profile: "Profile",
    // Projects
    createdByMe: "Created by me",
    joined: "Joined",
    search: "Search",
    createProject: "Create project",
    joinProject: "Join project",
    projectName: "Project Name",
    company: "Company",
    description: "Description",
    ndaText: "NDA Text",
    // Project details
    general: "General",
    tasks: "Tasks",
    documents: "Documents",
    projectDescription: "Project Description",
    participants: "Participants",
    addParticipant: "Add Participant",
    reports: "Reports",
    newReport: "New Report",
    submitReport: "Submit Report",
    noTasks: "No tasks for this filter",
    uploadFile: "Upload File",
    noDocuments: "No documents yet",
    createNewTask: "Create new task",
    // Task
    taskTitle: "Task Title",
    deadline: "Deadline",
    importance: "Importance",
    important: "Important",
    createTask: "Create Task",
    selectDeadline: "Select deadline date",
    project: "Project",
    // Task actions
    taskActions: "Task Actions",
    markAs: "Mark as",
    delete: "Delete",
    deleteTask: "Delete task?",
    cannotUndo: "This cannot be undone.",
    cancel: "Cancel",
    // Invite
    participantEmail: "Participant Email",
    sendInvite: "Send Invite",
    inviteCode: "Invite Code",
    inviteAnother: "Invite Another",
    inviteDisclaimer: "New participant joins the project only after signing NDA and accepting project rules.",
    // Profile
    personalInfo: "Personal Info",
    language: "Language",
    mode: "Mode",
    notifications: "Notifications",
    feedback: "Feedback",
    accountSettings: "Account Settings",
    exitAccount: "Exit account",
    exitConfirm: "Are you sure you want to exit?",
    exit: "Exit",
    // Personal info
    accountDetails: "Account Details",
    role: "Role",
    joinedDate: "Joined",
    security: "Security",
    // Settings
    comingSoon: "Coming soon",
    languageHint: "Language preference is saved locally on this device.",
    themeHint: "Theme preference is saved locally on this device.",
    notifHint: "Notification preferences are saved locally on this device.",
    light: "Light",
    dark: "Dark",
    system: "System",
    enableNotifications: "Enable Notifications",
    taskUpdates: "Task Updates",
    ndaAlerts: "NDA Alerts",
    newMembers: "New Members",
    howImprove: "How can we improve BlockSign?",
    tellUs: "Tell us what you think...",
    submitFeedback: "Submit Feedback",
    thankYou: "Thank you!",
    feedbackSubmitted: "Your feedback has been submitted.",
    account: "Account",
    changePassword: "Change Password",
    change: "Change",
    dangerZone: "Danger Zone",
    deleteAccount: "Delete Account",
    deleteAccountConfirm: "Are you sure? This action cannot be undone.",
    logOut: "Log Out",
    contentActivity: "Content & Activity",
    error: "Error",
    fillAllFields: "Please fill in all fields",
    loginFailed: "Login failed",
    checkCredentials: "Check your credentials",
    registrationFailed: "Registration failed",
    tryAgain: "Try again",
    projectNameRequired: "Project name is required",
    taskTitleRequired: "Task title is required",
    enterEmail: "Please enter participant's email",
    enterFeedback: "Please enter your feedback",
    // Statuses
    all: "All",
    inProgress: "In Progress",
    highPriority: "High Priority",
    notStarted: "Not Started",
    done: "Done",
    missed: "Missed",
    seeAll: "See All",
  },
  ru: {
    welcome: "Добро пожаловать",
    welcomeSubtitle: "Управляйте проектами, задачами и документами в одном месте.",
    logIn: "Войти",
    signUp: "Регистрация",
    email: "Email",
    password: "Пароль",
    fullName: "Полное имя",
    continue: "Продолжить",
    createAccount: "Создать аккаунт",
    noAccount: "Нет аккаунта? Зарегистрироваться",
    hasAccount: "Уже есть аккаунт? Войти",
    home: "Главная",
    myProjects: "Мои проекты",
    profile: "Профиль",
    createdByMe: "Созданные мной",
    joined: "Участвую",
    search: "Поиск",
    createProject: "Создать проект",
    joinProject: "Присоединиться",
    projectName: "Название проекта",
    company: "Компания",
    description: "Описание",
    ndaText: "Текст NDA",
    general: "Общее",
    tasks: "Задачи",
    documents: "Документы",
    projectDescription: "Описание проекта",
    participants: "Участники",
    addParticipant: "Добавить участника",
    reports: "Отчёты",
    newReport: "Новый отчёт",
    submitReport: "Отправить отчёт",
    noTasks: "Нет задач для этого фильтра",
    uploadFile: "Загрузить файл",
    noDocuments: "Документов пока нет",
    createNewTask: "Создать задачу",
    taskTitle: "Название задачи",
    deadline: "Дедлайн",
    importance: "Важность",
    important: "Важная",
    createTask: "Создать задачу",
    selectDeadline: "Выберите дату дедлайна",
    project: "Проект",
    taskActions: "Действия",
    markAs: "Отметить как",
    delete: "Удалить",
    deleteTask: "Удалить задачу?",
    cannotUndo: "Это действие нельзя отменить.",
    cancel: "Отмена",
    participantEmail: "Email участника",
    sendInvite: "Отправить приглашение",
    inviteCode: "Код приглашения",
    inviteAnother: "Пригласить ещё",
    inviteDisclaimer: "Новый участник присоединится к проекту только после подписания NDA.",
    personalInfo: "Личные данные",
    language: "Язык",
    mode: "Тема",
    notifications: "Уведомления",
    feedback: "Обратная связь",
    accountSettings: "Настройки аккаунта",
    exitAccount: "Выход",
    exitConfirm: "Вы уверены, что хотите выйти?",
    exit: "Выйти",
    accountDetails: "Данные аккаунта",
    role: "Роль",
    joinedDate: "Дата регистрации",
    security: "Безопасность",
    languageHint: "Язык сохраняется локально на устройстве.",
    themeHint: "Тема сохраняется локально на устройстве.",
    notifHint: "Настройки уведомлений сохраняются локально.",
    light: "Светлая",
    dark: "Тёмная",
    system: "Системная",
    enableNotifications: "Включить уведомления",
    taskUpdates: "Обновления задач",
    ndaAlerts: "Уведомления NDA",
    newMembers: "Новые участники",
    howImprove: "Как мы можем улучшить BlockSign?",
    tellUs: "Напишите ваши мысли...",
    submitFeedback: "Отправить отзыв",
    thankYou: "Спасибо!",
    feedbackSubmitted: "Ваш отзыв отправлен.",
    account: "Аккаунт",
    changePassword: "Изменить пароль",
    change: "Изменить",
    dangerZone: "Опасная зона",
    deleteAccount: "Удалить аккаунт",
    deleteAccountConfirm: "Вы уверены? Это действие нельзя отменить.",
    logOut: "Выйти",
    contentActivity: "Контент и активность",
    error: "Ошибка",
    fillAllFields: "Заполните все поля",
    loginFailed: "Ошибка входа",
    checkCredentials: "Проверьте данные",
    registrationFailed: "Ошибка регистрации",
    tryAgain: "Попробуйте снова",
    projectNameRequired: "Название проекта обязательно",
    taskTitleRequired: "Название задачи обязательно",
    enterEmail: "Введите email участника",
    enterFeedback: "Введите ваш отзыв",
    all: "Все",
    inProgress: "В процессе",
    highPriority: "Важные",
    notStarted: "Не начаты",
    done: "Готово",
    missed: "Пропущено",
    seeAll: "Все",
    comingSoon: "Скоро",
  },
  kz: {
    welcome: "Қош келдіңіз",
    welcomeSubtitle: "Жобаларды, тапсырмаларды және құжаттарды бір жерде басқарыңыз.",
    logIn: "Кіру",
    signUp: "Тіркелу",
    email: "Email",
    password: "Құпия сөз",
    fullName: "Толық аты",
    continue: "Жалғастыру",
    createAccount: "Аккаунт жасау",
    noAccount: "Аккаунт жоқ па? Тіркелу",
    hasAccount: "Аккаунт бар ма? Кіру",
    home: "Басты бет",
    myProjects: "Менің жобаларым",
    profile: "Профиль",
    createdByMe: "Мен жасағандар",
    joined: "Қатысамын",
    search: "Іздеу",
    createProject: "Жоба жасау",
    joinProject: "Қосылу",
    projectName: "Жоба атауы",
    company: "Компания",
    description: "Сипаттама",
    ndaText: "NDA мәтіні",
    general: "Жалпы",
    tasks: "Тапсырмалар",
    documents: "Құжаттар",
    projectDescription: "Жоба сипаттамасы",
    participants: "Қатысушылар",
    addParticipant: "Қатысушы қосу",
    reports: "Есептер",
    newReport: "Жаңа есеп",
    submitReport: "Есепті жіберу",
    noTasks: "Бұл сүзгі үшін тапсырмалар жоқ",
    uploadFile: "Файл жүктеу",
    noDocuments: "Құжаттар әлі жоқ",
    createNewTask: "Жаңа тапсырма жасау",
    taskTitle: "Тапсырма атауы",
    deadline: "Мерзім",
    importance: "Маңыздылық",
    important: "Маңызды",
    createTask: "Тапсырма жасау",
    selectDeadline: "Мерзімді таңдаңыз",
    project: "Жоба",
    taskActions: "Әрекеттер",
    markAs: "Белгілеу",
    delete: "Жою",
    deleteTask: "Тапсырманы жою?",
    cannotUndo: "Бұл әрекетті қайтару мүмкін емес.",
    cancel: "Бас тарту",
    participantEmail: "Қатысушы email",
    sendInvite: "Шақыру жіберу",
    inviteCode: "Шақыру коды",
    inviteAnother: "Тағы шақыру",
    inviteDisclaimer: "Жаңа қатысушы NDA қол қойғаннан кейін ғана қосылады.",
    personalInfo: "Жеке мәліметтер",
    language: "Тіл",
    mode: "Тақырып",
    notifications: "Хабарландырулар",
    feedback: "Кері байланыс",
    accountSettings: "Аккаунт баптаулары",
    exitAccount: "Шығу",
    exitConfirm: "Шығуға сенімдісіз бе?",
    exit: "Шығу",
    accountDetails: "Аккаунт мәліметтері",
    role: "Рөлі",
    joinedDate: "Тіркелген күні",
    security: "Қауіпсіздік",
    languageHint: "Тіл құрылғыда жергілікті сақталады.",
    themeHint: "Тақырып құрылғыда жергілікті сақталады.",
    notifHint: "Хабарландыру баптаулары жергілікті сақталады.",
    light: "Жарық",
    dark: "Қараңғы",
    system: "Жүйелік",
    enableNotifications: "Хабарландыруларды қосу",
    taskUpdates: "Тапсырма жаңартулары",
    ndaAlerts: "NDA хабарландырулар",
    newMembers: "Жаңа қатысушылар",
    howImprove: "BlockSign-ді қалай жақсарта аламыз?",
    tellUs: "Пікіріңізді жазыңыз...",
    submitFeedback: "Пікір жіберу",
    thankYou: "Рахмет!",
    feedbackSubmitted: "Пікіріңіз жіберілді.",
    account: "Аккаунт",
    changePassword: "Құпия сөзді өзгерту",
    change: "Өзгерту",
    dangerZone: "Қауіпті аймақ",
    deleteAccount: "Аккаунтты жою",
    deleteAccountConfirm: "Сенімдісіз бе? Бұл әрекетті қайтару мүмкін емес.",
    logOut: "Шығу",
    contentActivity: "Мазмұн және белсенділік",
    error: "Қате",
    fillAllFields: "Барлық өрістерді толтырыңыз",
    loginFailed: "Кіру қатесі",
    checkCredentials: "Деректерді тексеріңіз",
    registrationFailed: "Тіркелу қатесі",
    tryAgain: "Қайтадан көріңіз",
    projectNameRequired: "Жоба атауы міндетті",
    taskTitleRequired: "Тапсырма атауы міндетті",
    enterEmail: "Қатысушы email енгізіңіз",
    enterFeedback: "Пікіріңізді енгізіңіз",
    all: "Барлығы",
    inProgress: "Орындалуда",
    highPriority: "Маңызды",
    notStarted: "Басталмаған",
    done: "Дайын",
    missed: "Өткізілген",
    seeAll: "Барлығы",
    comingSoon: "Жақында",
  },
};

type LangState = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LangState>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

const LANG_KEY = "app_language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((stored) => {
      if (stored === "en" || stored === "ru" || stored === "kz") {
        setLangState(stored);
      }
      setLoaded(true);
    });
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    AsyncStorage.setItem(LANG_KEY, l);
  };

  const t = (key: string) => translations[lang][key] || translations.en[key] || key;

  if (!loaded) return null;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
